wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1660328794.58789
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 31
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 31
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 3
      - 23
      4: 3.9.13
      5: 0.13.1
      6: 4.20.1
      8:
      - 1
      - 5
